import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Button from 'react-bootstrap/Button';
import { useRouter } from 'next/router';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Navbar from 'react-bootstrap/Navbar';
import Link from 'next/link';

export default function MyNavbar() {
  // Logout function for btn
  const logout = () => {
    sessionStorage.removeItem('Token');
    router.push('/login');
  };

  return (
    <>
      <Head>
        <title>School CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar>
        <Container fluid>
          <Navbar.Brand href="/">Home</Navbar.Brand>
          <Navbar.Toggle />
          <Navbar.Collapse className="justify-content-end">
            <Link href="/">Home</Link>
            <Link href="/aessCourse">AESS Courses</Link>
            <Button size="sm" variant="dark" onClick={logout}>
              Log Out
            </Button>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    </>
  );
}
