import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Navbar() {
  return (
    <div className={styles.header}>
      <Head>
        <title>School CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>This is the Navbar!</p>
    </div>
  );
}
